#!/bin/sh

# if [ "`pwd`" != "$HOME" ] ;then
# 	cp $HOME/.gdbinit .gdbinit
# 	echo "set arg $*" >> .gdbinit
# fi

PWD="`pwd`"
EXEDIR="`dirname $0`"
# cd $EXEDIR

if [ "$GDB" = "" ] ;then
	GDB="gdb"
# 	GDB="ddd"
# 	GDB="gdb --async"
# 	GDB="gdbtui --async"
# 	GDB="gdb -w"
fi

ARGS=""
XGARG=""
while [ $# != 0 ] ;do
	case $1 in
		-XGraph)
			XGARG="-XGraph"
			;;
		-detach)
			;;
		-VisualType)
			ARGS="$ARGS $1 $2"
			shift
			;;
		-*|[0-9]*|\.*|/*)
			ARGS="$ARGS $1"
			;;
		\|*|python::*)
			ARGS="$ARGS \"$1\""
			;;
		*)
			ARGS="$ARGS \"$PWD/$1\""
			;;
	esac
	shift
done

echo "set arg -progname xgraph $XGARG -nodetach $ARGS -progname xgraph" > .gdb_args
echo "show arg" >> .gdb_args
exec ${GDB} -command=.gdb_args $EXEDIR/xgraph.bin

#!/bin/sh

# if [ "`pwd`" != "$HOME" ] ;then
# 	cp $HOME/.gdbinit .gdbinit
# 	echo "set arg $*" >> .gdbinit
# fi

echo "$$\nset arg $* -progname xgraph\nshow arg" > .gdb_args
exec gdb -command=.gdb_args $EXEDIR/xgraph.bin
