#!/bin/sh

cd `dirname $0`
echo $CWD

PVERSION=$1

headers() {
	case ${PVERSION} in
		23)
			INCLUDEPY="`python2.3 -c "from distutils import sysconfig ; print sysconfig.get_config_vars()['INCLUDEPY']"`"
			;;
		24)
			INCLUDEPY="`python2.4 -c "from distutils import sysconfig ; print sysconfig.get_config_vars()['INCLUDEPY']"`"
			;;
		25)
			INCLUDEPY="`python2.5 -c "from distutils import sysconfig ; print sysconfig.get_config_vars()['INCLUDEPY']"`"
			;;
		26)
			INCLUDEPY="`python2.6 -c "from distutils import sysconfig ; print sysconfig.get_config_vars()['INCLUDEPY']"`"
			;;
		27)
			INCLUDEPY="`python2.7 -c "import sysconfig ; print(sysconfig.get_config_vars()['INCLUDEPY'])"`"
			;;
		31)
			INCLUDEPY="`python3.1 -c "import sysconfig ; print(sysconfig.get_config_vars()['INCLUDEPY'])"`"
			;;
		32)
			INCLUDEPY="`python3.2 -c "import sysconfig ; print(sysconfig.get_config_vars()['INCLUDEPY'])"`"
			;;
		33)
			INCLUDEPY="`python3.3 -c "import sysconfig ; print(sysconfig.get_config_vars()['INCLUDEPY'])"`"
			;;
		sys|default)
			INCLUDEPY="`python -c "import sysconfig ; print(sysconfig.get_config_vars()['INCLUDEPY'])"`"
			;;
	esac

	echo "#include <${INCLUDEPY}/Python.h>" > python${PVERSION}_headers.h
	case ${PVERSION} in
		26|27)
			echo "#include <${INCLUDEPY}/bytesobject.h>" >> python${PVERSION}_headers.h
			echo "#include <${INCLUDEPY}/intobject.h>" >> python${PVERSION}_headers.h
			;;
		sys|default)
			echo "#include <${INCLUDEPY}/bytesobject.h>" >> python${PVERSION}_headers.h
			echo "#if PY_MAJOR_VERSION < 3" >> python${PVERSION}_headers.h
			echo "#	include <${INCLUDEPY}/intobject.h>" >> python${PVERSION}_headers.h
			echo "#endif" >> python${PVERSION}_headers.h
			;;
	esac
}

# create a the python<version>_numpy.h headerfile that will include arrayobject.h :
numpy() {
	case ${PVERSION} in
		23)
			echo "#include <"`python2.3 -c "import numpy ; print numpy.get_include()"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
		24)
			echo "#include <"`python2.4 -c "import numpy ; print numpy.get_include()"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
		25)
			echo "#include <"`python2.5 -c "import numpy ; print numpy.get_include()"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
		26)
			echo "#include <"`python2.6 -c "import numpy ; print numpy.get_include()"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
		27)
			echo "#include <"`python2.7 -c "import numpy ; print numpy.get_include()"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
		31)
			echo "#include <"`python3.1 -c "import numpy ; print(numpy.get_include())"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
		32)
			echo "#include <"`python3.2 -c "import numpy ; print(numpy.get_include())"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
		33)
			echo "#include <"`python3.3 -c "import numpy ; print(numpy.get_include())"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
		sys|default)
#		PVERSION=`echo "import sys ; print str(sys.version_info[0])+str(sys.version_info[1])" | python`${PVERSION}
			echo "#include <"`python -c "import numpy ; print numpy.get_include()"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
	esac
}

# retrieve the installation path of the selection Python version:
prefix() {
	case ${PVERSION} in
		23)
			echo 'import sys;print sys.prefix' | python2.3
			;;
		24)
			echo 'import sys;print sys.prefix' | python2.4
			;;
		25)
			echo 'import sys;print sys.prefix' | python2.5
			;;
		26)
			echo 'import sys;print sys.prefix' | python2.6
			;;
		27)
			echo 'import sys;print sys.prefix' | python2.7
			;;
		31)
			echo 'import sys;print(sys.prefix)' | python3.1
			;;
		32)
			echo 'import sys;print(sys.prefix)' | python3.2
			;;
		33)
			echo 'import sys;print(sys.prefix)' | python3.3
			;;
		sys|default)
			if [ "${PYTHON}" = "" ] ;then
				PYTHON="python"
			fi
			echo 'import sys;print sys.prefix' | ${PYTHON}
			;;
	esac
}

case $2 in
	headers)
		headers
		;;
	numpy)
		numpy
		;;
	*)
		prefix
		;;
esac
