#!/bin/sh

cd `dirname $0`
echo $CWD 1>&2

PVERSION=$1

headers() {
	case ${PVERSION} in
		23)
			CONFINCLUDEPY="`python2.3 -c "from distutils import sysconfig ; print sysconfig.get_config_vars()['CONFINCLUDEPY']"`"
			;;
		24)
			CONFINCLUDEPY="`python2.4 -c "from distutils import sysconfig ; print sysconfig.get_config_vars()['CONFINCLUDEPY']"`"
			;;
		25)
			CONFINCLUDEPY="`python2.5 -c "from distutils import sysconfig ; print sysconfig.get_config_vars()['CONFINCLUDEPY']"`"
			;;
		26)
			CONFINCLUDEPY="`python2.6 -c "from distutils import sysconfig ; print sysconfig.get_config_vars()['CONFINCLUDEPY']"`"
			;;
		27)
			CONFINCLUDEPY="`python2.7 -c "import sysconfig ; print(sysconfig.get_config_vars()['CONFINCLUDEPY'])"`"
			;;
		31)
			CONFINCLUDEPY="`python3.1 -c "import sysconfig ; print(sysconfig.get_config_vars()['CONFINCLUDEPY'])"`"
			;;
		32)
			CONFINCLUDEPY="`python3.2 -c "import sysconfig ; print(sysconfig.get_config_vars()['CONFINCLUDEPY'])"`"
			;;
		33)
			CONFINCLUDEPY="`python3.3 -c "import sysconfig ; print(sysconfig.get_config_vars()['CONFINCLUDEPY'])"`"
			;;
		34)
			CONFINCLUDEPY="`python3.4 -c "import sysconfig ; print(sysconfig.get_config_vars()['CONFINCLUDEPY'])"`"
			;;
		sys|default)
			CONFINCLUDEPY="`python -c "import sysconfig ; print(sysconfig.get_config_vars()['CONFINCLUDEPY'])"`"
			;;
	esac

	echo "#include <${CONFINCLUDEPY}/Python.h>" > python${PVERSION}_headers.h
	case ${PVERSION} in
		26|27)
			echo "#include <${CONFINCLUDEPY}/bytesobject.h>" >> python${PVERSION}_headers.h
			echo "#include <${CONFINCLUDEPY}/intobject.h>" >> python${PVERSION}_headers.h
			;;
		sys|default|*)
			echo "#include <${CONFINCLUDEPY}/bytesobject.h>" >> python${PVERSION}_headers.h
			echo "#if PY_MAJOR_VERSION < 3" >> python${PVERSION}_headers.h
			echo "#	include <${CONFINCLUDEPY}/intobject.h>" >> python${PVERSION}_headers.h
			echo "#endif" >> python${PVERSION}_headers.h
			;;
	esac
}

# create a the python<version>_numpy.h headerfile that will include arrayobject.h :
numpy() {
	case ${PVERSION} in
		23)
			echo "#include <"`python2.3 -c "import numpy ; print numpy.get_include()"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
		24)
			echo "#include <"`python2.4 -c "import numpy ; print numpy.get_include()"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
		25)
			echo "#include <"`python2.5 -c "import numpy ; print numpy.get_include()"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
		26)
			echo "#include <"`python2.6 -c "import numpy ; print numpy.get_include()"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
		27)
			echo "#include <"`python2.7 -c "import numpy ; print numpy.get_include()"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
		31)
			echo "#include <"`python3.1 -c "import numpy ; print(numpy.get_include())"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
		32)
			echo "#include <"`python3.2 -c "import numpy ; print(numpy.get_include())"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
		33)
			echo "#include <"`python3.3 -c "import numpy ; print(numpy.get_include())"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
		34)
			echo "#include <"`python3.4 -c "import numpy ; print(numpy.get_include())"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
		sys|default)
#		PVERSION=`echo "import sys ; print str(sys.version_info[0])+str(sys.version_info[1])" | python`${PVERSION}
			echo "#include <"`python -c "import numpy ; print numpy.get_include()"`"/numpy/arrayobject.h>" > python${PVERSION}_numpy.h
			;;
	esac
}

# retrieve the installation path of the selection Python version:
prefix() {
	case ${PVERSION} in
		23)
			echo 'import sys;print sys.prefix' | python2.3
			;;
		24)
			echo 'import sys;print sys.prefix' | python2.4
			;;
		25)
			echo 'import sys;print sys.prefix' | python2.5
			;;
		26)
			echo 'import sys;print sys.prefix' | python2.6
			;;
		27)
			echo 'import sys;print sys.prefix' | python2.7
			;;
		31)
			echo 'import sys;print(sys.prefix)' | python3.1
			;;
		32)
			echo 'import sys;print(sys.prefix)' | python3.2
			;;
		33)
			#echo 'import sys;print(sys.prefix)' | python3.3
			python3.3-config --prefix
			;;
		34)
			echo 'import sys;print(sys.prefix)' | python3.4
			;;
		sys|default)
			if [ "${PYTHON}" = "" ] ;then
				PYTHON="python"
			fi
			echo 'import sys;print sys.prefix' | ${PYTHON}
			;;
	esac
}

config() {
	case ${PVERSION} in
		25|Python25Module)
			echo python2.5-config
			;;
		26|Python26Module)
			echo python2.6-config
			;;
		27|Python27Module)
			echo python2.7-config
			;;
		31|Python31Module)
			echo python3.1-config
			;;
		32|Python32Module)
			echo python3.2-config
			;;
		33|Python33Module)
			echo python3.3-config
			;;
		34|Python34Module)
			echo python3.4-config
			;;
		sys|default|PythondefaultModule|PythonsysModule)
			echo python-config
			;;
	esac
}

case $2 in
	headers)
		headers
		;;
	numpy)
		numpy
		;;
	config)
		config
		;;
	*)
		prefix
		;;
esac
