#!/bin/sh

ACROREAD="/cygdrive/c/Program Files (x86)/Adobe/Reader 10.0/Reader/AcroRd32.exe"
CYGWINPATH="c:\\Developer\\cygwin"
PWD="`pwd | sed -e 's,/,\\\\,g'`"

ARGS=""
while [ $# != 0 ] ;do
	case ${1} in
		-*)
			ARGS="${ARGS} ${1}"
			;;
		/*)
			ARGS="${ARGS} ${CYGWINPATH}`echo ${1} | sed -e 's,/,\\\\,g'`"
			;;
		*)
			ARGS="${ARGS} ${CYGWINPATH}${PWD}\\`echo ${1} | sed -e 's,/,\\\\,g'`"
			;;
	esac
	shift
done

echo "${ACROREAD}" ${ARGS} 1>&2
exec "${ACROREAD}" ${ARGS}
