#!/bin/sh

if [ $# = 0 ] ;then
	exec Env
else
# 	if [ $# = 1 -o $# -gt 2 ] ;then
	if [ $# = 1 ] ;then
		echo "usage: `basename $0` <variablename> <value>"
		echo "The variable is recorded in \$ENVDIR , ./.env or $HOME/.env"
		exit 1
	fi
fi
if [ "$ENVDIR" = "" ] ;then
	if [ -d ./.env ] ;then
		ENVDIR="./.env"
	else	
		if [ -d $HOME/.env ] ;then
			ENVDIR="$HOME/.env"
		else
			echo "No ENVDIR specified - creating ./.env"
			mkdir ./.env
			ENVDIR="./.env"
		fi
	fi
fi

if [ ! -d "$ENVDIR" ] ;then
	echo "ENVDIR=$ENVDIR : not a directory"
	exit 10
fi

# VAR=$ENVDIR/$1
# shift
while [ $# -gt 1 ] ;do
	/bin/echo -n >$ENVDIR/$1 "$2"
	shift 2
done
