#!/bin/sh

echo
if [ "${WCONFIGUREENV}" = "" ] ;then
	WCONFIGUREENV="wconfigure.env"
	echo "# $0 $@" 1>&2
else
	echo "# env WCONFIGUREENV=\"${WCONFIGUREENV}\" $0 $@" 1>&2
fi
echo "# `date`" 1>&2

GCCOPT_SIMPLE=1 ; export GCCOPT_SIMPLE
GCCOPT_QUIET=1 ; export GCCOPT_QUIET

if [ "${CCMAKE}" = "" ] ;then
	CCMAKE=/opt/local/bin/ccmake
fi

# 20090106
# if [ "$MACOSX_DEPLOYMENT_TARGET" = "" ] ;then
# 	MACOSX_DEPLOYMENT_TARGET=10.3
# 	export MACOSX_DEPLOYMENT_TARGET
# fi

copy_envvars() {
	if [ "${CC}" != "" ] ;then
		CMAKE_C_COMPILER="${CMAKE_C_COMPILER} ${CC}" ; export CMAKE_C_COMPILER
	fi
	if [ "${CFLAGS}" != "" ] ;then
		CMAKE_C_FLAGS="${CMAKE_C_FLAGS} ${CPPFLAGS}" ; export CMAKE_C_FLAGS
		CMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} ${CPPFLAGS}" ; export CMAKE_CXX_FLAGS
	fi
	if [ "${CFLAGS}" != "" ] ;then
		CMAKE_C_FLAGS="${CMAKE_C_FLAGS} ${CFLAGS}" ; export CMAKE_C_FLAGS
	fi
	if [ "${CXX}" != "" ] ;then
		CMAKE_CXX_COMPILER="${CMAKE_CXX_COMPILER} ${CXX}" ; export CMAKE_CXX_COMPILER
	fi
	if [ "${CXXFLAGS}" != "" ] ;then
		CMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} ${CXXFLAGS}" ; export CMAKE_CXX_FLAGS
	fi
	if [ "${CMAKE_C_FLAGS}" != "" ] ;then
		CMAKE_C_FLAGS_DEBUG="${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_DEBUG}" ; export CMAKE_C_FLAGS_DEBUG
		CMAKE_C_FLAGS_RELEASE="${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_RELEASE}" ; export CMAKE_C_FLAGS_RELEASE
		CMAKE_C_FLAGS_RELWITHDEBINFO="${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_RELWITHDEBINFO}" ; export CMAKE_C_FLAGS_RELWITHDEBINFO
		echo "${CMAKE_C_FLAGS_RELEASE}"
	fi
	if [ "${CMAKE_CXX_FLAGS}" != "" ] ;then
		CMAKE_CXX_FLAGS_DEBUG="${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_DEBUG}" ; export CMAKE_CXX_FLAGS_DEBUG
		CMAKE_CXX_FLAGS_RELEASE="${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_RELEASE}" ; export CMAKE_CXX_FLAGS_RELEASE
		CMAKE_CXX_FLAGS_RELWITHDEBINFO="${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_RELWITHDEBINFO}" ; export CMAKE_CXX_FLAGS_RELWITHDEBINFO
		echo "${CMAKE_CXX_FLAGS_RELEASE}"
	fi
}

if [ "$NOWCC" != "" ] ;then
	KK="kk$$"
	${NOWCC} -cli > ${KK} 2>/dev/null
	compiler="`fgrep 'compiler=' ${KK} | sed -e 's/compiler=\([^ ]*\).*/\1/'`" ; export compiler
	CPP="`fgrep 'CPP=' ${KK} | sed -e 's/CPP=\([^ ]*\).*/\1/'`" ; export CPP
	CC="`fgrep 'CC=' ${KK} | sed -e 's/CC=\([^ ]*\).*/\1/'`" ; export CC
	OPTS=`fgrep 'CC=' ${KK} | sed -e 's/CC=\([^ ]*\)\(.*\)/\2/'`
	CPPFLAGS=`fgrep CPPFLAGS= ${KK} | sed -e 's/CPPFLAGS=//'` ; export CPPFLAGS
	CFLAGS=`fgrep CFLAGS= ${KK} | sed -e 's/CFLAGS=//'`
	CFLAGS="${OPTS}${CFLAGS}" ; export CFLAGS
	CXX="$CC" ; export CXX
	CXXFLAGS="$CFLAGS" ; export CXXFLAGS
	OBJC="${CC}" ; export OBJC
	OBJCFLAGS="${CFLAGS} ${OBJCFLAGS}" ; export OBJCFLAGS
	if [ "$MACOSX_DEPLOYMENT_TARGET" = "" ] ;then
		macosx_deployment_target="`fgrep 'MACOSX_DEPLOYMENT_TARGET=' ${KK} | sed -e 's/MACOSX_DEPLOYMENT_TARGET=\([^ ]*\).*/\1/'`"
		if [ "$macosx_deployment_target" != "" ] ;then
			MACOSX_DEPLOYMENT_TARGET="${macosx_deployment_target}" ; export MACOSX_DEPLOYMENT_TARGET
		fi
	fi
	if [ "$GCC" = "" ] ;then
		GCC="${CC}" ; export GCC
	fi
	if [ "$GXX" = "" ] ;then
		GXX="${CXX}" ; export GXX
	fi
	rm -f ${KK}
	copy_envvars
	echo "${CCMAKE} $@"
	${CCMAKE} "$@"
	RET=$?
else
	if [ -r "${WCONFIGUREENV}" ] ;then
		. "${WCONFIGUREENV}"
	fi
	copy_envvars
	${CCMAKE} "$@"
	RET=$?
fi
times
echo "# `date`" 1>&2
exit $RET
