#!/bin/bash

ECHO=/bin/echo
export ECHO

RWSTRINGS=0 ; export RWSTRINGS

if [ "${1}" = "-E" -a "${2}" = "server" ] ;then
	# emulate the error message from an older CMake version
	(   echo "CMake Error: cmake version 3.0.1 (faked to avoid server mode)"
	    echo "Usage: /opt/local/bin/cmake -E [command] [arguments ...]"
	) 1>&2
	exit 1
fi

if [ "${WCONFIGURE}" = "" ] ;then
	WCONFIGURE="./wconfigure.env"
	WCMAKECALL="./wcmake.call"
	echo "# $0 $@" 1>&2
else
	WDIR=`dirname "${WCONFIGURE}"`
	if [ ! -w "${WDIR}" ] ;then
		WDIR="."
	fi
	WCMAKECALL="${WDIR}"/wcmake.call
	echo "# env WCONFIGURE=\"${WCONFIGURE}\" WCMAKECALL=\"${WCMAKECALL}\" $0 $@" 1>&2
fi

if [ "$1" == "--MP" ] ;then
	CC_PRINT_OPTIONS=YES ; export CC_PRINT_OPTIONS
	CPATH=/opt/local/include ; export CPATH
	INSTALL="/usr/bin/install -c" ; export INSTALL
	LIBRARY_PATH=/opt/local/lib ; export LIBRARY_PATH
	MOC=/opt/local/bin/moc ; export MOC
	PATH=.:/Users/bertin/bin:/Users/bertin/script:./script:/opt/local/bin:/opt/local/sbin:/usr/bin/X11:/bin:/sbin:/usr/bin:/usr/sbin
	export PATH
	QMAKE=/opt/local/bin/qmake ; export QMAKE
	QTDIR=/opt/local ; export QTDIR
	MACPORTS=1
	shift 1
fi

if [ "${WCMAKEARGS}" = "" ] ;then
	WCMAKEARGS="./wcmake.args"
fi
if [ -r "${WCMAKEARGS}" ] ;then
	ARGS=`cat "${WCMAKEARGS}"`
else
	ARGS=""
fi

if [ "$CMAKEAPP" = "" ] ;then
	if [ "`basename $0`" = "cmake" ] ;then
		# WE GUESS:
		CMAKEAPP="/usr/bin/cmake"
	else
		CMAKEAPP="cmake"
	fi
fi

# save vars passed on the commandline to override those in wconfigure.env:
cliCPP="${CPP}"
cliCC="${CC}"
cliCXX="${CXX}"
cliOBJC="${OBJC}"
cliF77="${F77}"
cliFC="${FC}"
cliCPPFLAGS="${CPPFLAGS}"
cliCFLAGS="${CFLAGS}"
cliOBJCFLAGS="${OBJCFLAGS}"
cliCXXFLAGS="${CXXFLAGS}"
cliFFLAGS="${FFLAGS}"
cliFCFLAGS="${FCFLAGS}"
cliPYTHON="${PYTHON}"
cliPYTHONPATH="${PYTHONPATH}"
cliMACOSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET}"

if [ "${WCONFIGURE}" = "/dev/null" -o "${WCONFIGURE}" = "none" ] ;then
	NOWCC="none"
else
	if [ -r "${WCONFIGURE}" ] ;then
		. "${WCONFIGURE}"
	fi
fi

if [ "${cliCPP}" != "" ] ;then
	CPP="${cliCPP}" ; export CPP
fi
if [ "${cliCC}" != "" ] ;then
	CC="${cliCC}" ; export CC
fi
if [ "${cliCXX}" != "" ] ;then
	CXX="${cliCXX}" ; export CXX
fi
if [ "${cliOBJC}" != "" ] ;then
	OBJC="${cliOBJC}" ; export OBJC
fi
if [ "${cliF77}" != "" ] ;then
	F77="${cliF77}" ; export F77
fi
if [ "${cliFC}" != "" ] ;then
	FC="${cliFC}" ; export FC
fi
if [ "${cliCPPFLAGS}" != "" ] ;then
	CPPFLAGS="${cliCPPFLAGS}" ; export CPPFLAGS
fi
if [ "${cliCFLAGS}" != "" ] ;then
	CFLAGS="${cliCFLAGS}" ; export CFLAGS
fi
if [ "${cliOBJCFLAGS}" != "" ] ;then
	OBJCFLAGS="${cliOBJCFLAGS}" ; export OBJCFLAGS
fi
if [ "${cliCXXFLAGS}" != "" ] ;then
	CXXFLAGS="${cliCXXFLAGS}" ; export CXXFLAGS
fi
if [ "${cliFFLAGS}" != "" ] ;then
	FFLAGS="${cliFFLAGS}" ; export FFLAGS
fi
if [ "${cliFCFLAGS}" != "" ] ;then
	FCFLAGS="${cliFCFLAGS}" ; export FCFLAGS
fi
if [ "${cliPYTHON}" != "" ] ;then
	PYTHON="${cliPYTHON}" ; export PYTHON
fi
if [ "${cliPYTHONPATH}" != "" ] ;then
	PYTHONPATH="${cliPYTHONPATH}" ; export PYTHONPATH
fi
if [ "${cliMACOSX_DEPLOYMENT_TARGET}" != "" ] ;then
	MACOSX_DEPLOYMENT_TARGET="${cliMACOSX_DEPLOYMENT_TARGET}" ; export MACOSX_DEPLOYMENT_TARGET
fi
#set -x

# set NOWCC to the desired compiler script in order to attempt to retrieve its CC and CFLAGS settings
# and pass those directly to cmake .. This may be necessary when the compiler is called from within
# libtool.
if [ "$NOWCC" != "" ] ;then
	case $NOWCC in
		default|system|none|1)
			${ECHO} "Using (provided) defaults: CPP=${CPP} CC=${CC} CPPFLAGS=${CPPFLAGS} CFLAGS=${CFLAGS} CXX=${CXX} CXXFLAGS=${CXXFLAGS} OBJC=${OBJC} OBJCFLAGS=${OBJCFLAGS} F77=${F77} FFLAGS=${FFLAGS} FC=${FC} FCFLAGS=${FCFLAGS} PYTHON=${PYTHON} PYTHONPATH=${PYTHONPATH}"
			;;
		*)
			KK="kk$$"
			${NOWCC} -cli > ${KK}
			CPP="`fgrep 'CPP=' ${KK} | sed -e 's/CPP=\([^ ]*\).*/\1/'`" ; export CPP
			CC="`fgrep 'CC=' ${KK} | sed -e 's/CC=\([^ ]*\).*/\1/'`" ; export CC
			OPTS=`fgrep 'CC=' ${KK} | sed -e 's/CC=\([^ ]*\)\(.*\)/\2/'`
			CPPFLAGS="`fgrep CPPFLAGS= ${KK} | sed -e 's/CPPFLAGS=//'` ${CPPFLAGS}" ; export CPPFLAGS
			CFLAGS="`fgrep CFLAGS= ${KK} | sed -e 's/CFLAGS=//'` ${CFLAGS}"
			CFLAGS="${OPTS}${CFLAGS}" ; export CFLAGS
			CXX="`${ECHO} ${CC} | sed -e 's/gcc/g++/g'`" ; export CXX
			CXXFLAGS="${CFLAGS} ${CXXFLAGS}" ; export CXXFLAGS
			OBJC="${CC}" ; export OBJC
			OBJCFLAGS="${CFLAGS} ${OBJCFLAGS}" ; export OBJCFLAGS
			PYTHON="${PYTHON}" ; export PYTHON
			PYTHONPATH="${PYTHONPATH}" ; export PYTHONPATH
			macosx_deployment_target="`fgrep 'MACOSX_DEPLOYMENT_TARGET=' ${KK} | sed -e 's/MACOSX_DEPLOYMENT_TARGET=\([^ ]*\).*/\1/'`"
			rm -f ${KK}
			;;
	esac
else
	if [ "$CC" = "" ] ;then
		CC=wcc ; export CC
		${CC} -cli
	fi
	if [ "$CXX" = "" ] ;then
		CXX=w++ ; export CXX
	fi
	if [ "$OBJC" = "" ] ;then
		OBJC=wcc ; export OBJC
		${OBJC} -cli
	fi
	if [ "$F77" = "" ] ;then
		F77=w77 ; export F77
	fi
	if [ "$FC" = "" ] ;then
		FC=w95 ; export FC
		${FC} -cli
	fi
	if [ "$CPPFLAGS" = "" ] ;then
		CPPFLAGS="" ; export CPPFLAGS
	fi
	if [ "$CFLAGS" = "" ] ;then
		CFLAGS="" ; export CFLAGS
	fi
	if [ "$OBJCFLAGS" = "" ] ;then
		OBJCFLAGS="" ; export OBJCFLAGS
	fi
	if [ "$CXXFLAGS" = "" ] ;then
		CXXFLAGS="" ; export CXXFLAGS
	fi
	if [ "$FFLAGS" = "" ] ;then
		FFLAGS="" ; export FFLAGS
	fi
	if [ "$FCFLAGS" = "" ] ;then
		FCFLAGS="" ; export FCFLAGS
	fi
	if [ "$PYTHON" = "" ] ;then
		PYTHON="" ; export PYTHON
	fi
	if [ "$PYTHONPATH" = "" ] ;then
		PYTHONPATH="" ; export PYTHONPATH
	fi
	if [ "$MACOSX_DEPLOYMENT_TARGET" = "" ] ;then
		if [ "$macosx_deployment_target" != "" ] ;then
			MACOSX_DEPLOYMENT_TARGET="${macosx_deployment_target}" ; export MACOSX_DEPLOYMENT_TARGET
		fi
	fi
fi

# For those cmake set-ups that do not support CPPFLAGS: if requested, merge
# those flags into CFLAGS.
if [ $MERGE_CPPFLAGS ] ;then
	CFLAGS="${CPPFLAGS} ${CFLAGS}" ; export CFLAGS
	CPPFLAGS="" ; export CPPFLAGS
fi

GCCOPT_SIMPLE=1 ; export GCCOPT_SIMPLE
GCCOPT_QUIET=1 ; export GCCOPT_QUIET

if [ "$WCC_STUB" = "" ] ;then
	WCC_STUB=1 ; export WCC_STUB
fi

pwd
# ${ECHO} "env compiler=\"${compiler}\" CMAKEAPP=\"${CMAKEAPP}\" NOWCC=\"${NOWCC}\" WCC_STUB=\"${WCC_STUB}\" `basename $0` $@"
# ${ECHO} "USE_GNOME_DIR=${USE_GNOME_DIR} LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"

${ECHO} -n "env HOST=\"${HOST}\"" > "${WCMAKECALL}"
if [ "$LD_LIBRARY_PATH" != "" ] ;then
	${ECHO} -n " LD_LIBRARY_PATH=\"${LD_LIBRARY_PATH}\"" >> "${WCMAKECALL}"
fi
if [ "$USE_GNOME_DIR" != "" ] ;then
	${ECHO} -n " USE_GNOME_DIR=\"${USE_GNOME_DIR}\"" >> "${WCMAKECALL}"
fi
if [ "$DYLD_LIBRARY_PATH" != "" ] ;then
	${ECHO} -n " DYLD_LIBRARY_PATH=\"${DYLD_LIBRARY_PATH}\"" >> "${WCMAKECALL}"
fi
if [ "$MACOSX_DEPLOYMENT_TARGET" != "" ] ;then
	${ECHO} -n " MACOSX_DEPLOYMENT_TARGET=\"${MACOSX_DEPLOYMENT_TARGET}\"" >> "${WCMAKECALL}"
fi
if [ "$PYTHON" != "" ] ;then
	${ECHO} -n " PYTHON=\"${PYTHON}\" ; export PYTHON" >> "${WCMAKECALL}"
fi
if [ "$PYTHONPATH" != "" ] ;then
	${ECHO} -n " PYTHONPATH=\"${PYTHONPATH}\" ; export PYTHONPATH" >> "${WCMAKECALL}"
fi
if [ "${compiler}" != "" ] ;then
	${ECHO} -n " compiler=\"${compiler}\"" >> "${WCMAKECALL}"
fi
${ECHO} -n " CMAKEAPP=\"${CMAKEAPP}\"" >> "${WCMAKECALL}"
if [ "$NOWCC" != "" ] ;then
	${ECHO} -n " NOWCC=\"${NOWCC}\"" >> "${WCMAKECALL}"
fi
if [ $WCC_STUB != 1 ] ;then
	${ECHO} -n " WCC_STUB=\"${WCC_STUB}\"" >> "${WCMAKECALL}"
fi
${ECHO} -n " `basename $0`" >> "${WCMAKECALL}"
if [ "${MACPORTS}" != "" ] ;then
	${ECHO} -n " --MP" >> "${WCMAKECALL}"
fi
${ECHO} " $@" >> "${WCMAKECALL}"

if [ "${WCONFIGURE}" != "/dev/null" ] ;then
	rm "${WCONFIGURE}"
fi
rm -f ./wcmake.initcache
if [ "${compiler}" != "" ] ;then
	${ECHO} "compiler=\"${compiler}\" ; export compiler" >> "${WCONFIGURE}"
fi
if [ "${CPP}" != "" ] ;then
	${ECHO} "CPP=\"${CPP}\" ; export CPP" >> "${WCONFIGURE}"
fi
if [ "${CC}" != "" ] ;then
	${ECHO} "CC=\"${CC}\"" >> "${WCONFIGURE}"
	#ARGS+=" \"-DCMAKE_C_COMPILER:FILEPATH=${CC}\""
	${ECHO} "SET (CMAKE_C_COMPILER:FILEPATH \"${CC}\")" >> ./wcmake.initcache
fi
${ECHO} "CPPFLAGS=\"${CPPFLAGS}\"" >> "${WCONFIGURE}"
if [ "${CFLAGS}" != "" ] ;then
	${ECHO} "CFLAGS=\"${CFLAGS}\"" >> "${WCONFIGURE}"
	#ARGS+=" -DCMAKE_C_FLAGS:STRING=`echo ${CFLAGS} | sed -e 's/ /\\\\ /g'`"
	${ECHO} "SET (CMAKE_C_FLAGS:STRING \"${CFLAGS}\")" >> ./wcmake.initcache
	${ECHO} "SET (CMAKE_C_FLAGS_RELEASE:STRING \"${CFLAGS}\")" >> ./wcmake.initcache
	${ECHO} "SET (CMAKE_C_FLAGS_RELWITHDEBINFO:STRING \"${CFLAGS} -g\")" >> ./wcmake.initcache
fi
if [ "${CXX}" != "" ] ;then
	${ECHO} "CXX=\"${CXX}\"" >> "${WCONFIGURE}"
 	#ARGS+=" \"-DCMAKE_CXX_COMPILER:FILEPATH=${CXX}\""
	${ECHO} "SET (CMAKE_CXX_COMPILER:FILEPATH \"${CXX}\")" >> ./wcmake.initcache
fi
if [ "${CXXFLAGS}" != "" ] ;then
	if [ "${CXXFLAGS}" = "${CFLAGS}" ] ;then
		${ECHO} 'CXXFLAGS="${CFLAGS}"' >> "${WCONFIGURE}"
	else
		${ECHO} "CXXFLAGS=\"${CXXFLAGS}\"" >> "${WCONFIGURE}"
	fi
 	#ARGS+=" -DCMAKE_CXX_FLAGS:STRING=${CXXFLAGS}"
 	${ECHO} "SET (CMAKE_CXX_FLAGS:STRING \"${CXXFLAGS}\")" >> ./wcmake.initcache
 	${ECHO} "SET (CMAKE_CXX_FLAGS_RELEASE:STRING \"${CXXFLAGS}\")" >> ./wcmake.initcache
 	${ECHO} "SET (CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING \"${CXXFLAGS} -g\")" >> ./wcmake.initcache
fi
if [ "${OBJC}" = "${CC}" ] ;then
	${ECHO} 'OBJC="${CC}"' >> "${WCONFIGURE}"
else
	${ECHO} "OBJC=\"${OBJC}\"" >> "${WCONFIGURE}"
fi
if [ "${OBJCFLAGS}" = "${CFLAGS}" ] ;then
	${ECHO} 'OBJCFLAGS="${CFLAGS}"' >> "${WCONFIGURE}"
else
	${ECHO} "OBJCFLAGS=\"${OBJCFLAGS}\"" >> "${WCONFIGURE}"
fi
${ECHO} "F77=\"${F77}\"" >> "${WCONFIGURE}"
if [ "${FFLAGS}" = "${CFLAGS}" ] ;then
	${ECHO} 'FFLAGS="${CFLAGS}"' >> "${WCONFIGURE}"
else
	${ECHO} "FFLAGS=\"${FFLAGS}\"" >> "${WCONFIGURE}"
fi
if [ "${FC}" = "${F77}" ] ;then
	${ECHO} 'FC="${F77}"' >> "${WCONFIGURE}"
else
	${ECHO} "FC=\"${FC}\"" >> "${WCONFIGURE}"
fi
if [ "${FCFLAGS}" = "${CFLAGS}" ] ;then
	${ECHO} 'FCFLAGS="${CFLAGS}"' >> "${WCONFIGURE}"
elif [ "${FCFLAGS}" = "${FFLAGS}" ] ;then
	${ECHO} 'FCFLAGS="${FFLAGS}"' >> "${WCONFIGURE}"
else
	${ECHO} "FCFLAGS=\"${FCFLAGS}\"" >> "${WCONFIGURE}"
fi
if [ "${LDFLAGS}" != "" ] ;then
	${ECHO} "LDFLAGS=\"${LDFLAGS}\"" >> "${WCONFIGURE}"
	#ARGS+=" \"-DCMAKE_EXE_LINKER_FLAG:STRINGS=${LDFLAGS}\""
	${ECHO} "SET (CMAKE_EXE_LINKER_FLAG:STRINGS \"${LDFLAGS}\")" >> ./wcmake.initcache
fi
if [ "$MACOSX_DEPLOYMENT_TARGET" != "" ] ;then
	${ECHO} "MACOSX_DEPLOYMENT_TARGET=\"${MACOSX_DEPLOYMENT_TARGET}\" ; export MACOSX_DEPLOYMENT_TARGET" >> "${WCONFIGURE}"
fi
if [ "$PYTHON" != "" ] ;then
	${ECHO} "PYTHON=\"${PYTHON}\" ; export PYTHON" >> "${WCONFIGURE}"
fi
if [ "$PYTHONPATH" != "" ] ;then
	${ECHO} "PYTHONPATH=\"${PYTHONPATH}\" ; export PYTHONPATH" >> "${WCONFIGURE}"
fi
${ECHO} "export CC CPPFLAGS CFLAGS CXX CXXFLAGS OBJC OBJCFLAGS F77 FFLAGS FC FCFLAGS LDFLAGS" >> "${WCONFIGURE}"

if [ -r ./wcmake.initcache ] ;then
	if [ "$1" = "-E" -a "$2" = "server" ] ;then
		exec "${CMAKEAPP}" "$@"
	else
		exec "${CMAKEAPP}" -C./wcmake.initcache ${ARGS} "$@"
	fi
else
	exec "${CMAKEAPP}" ${ARGS} "$@"
fi
